name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase service account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ~/firebase-key.json

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project=fxc-app-47e5d --token "$(cat ~/firebase-key.json | jq -r .token)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ~/firebase-key.json
